# Generated by Django 4.0 on 2022-01-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Crypto_comprada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.billetera')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crypto')),
            ],
        ),
        migrations.CreateModel(
            name='User_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateField(auto_now_add=True)),
                ('cant_1', models.FloatField()),
                ('cant_2', models.FloatField(blank=True)),
                ('type_of_order', models.CharField(choices=[('compra', 'compra'), ('venta', 'venta')], default='compra', max_length=10)),
                ('message', models.TextField()),
                ('coin_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crypto_comprada')),
                ('coin_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crypto')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.billetera')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('picture', models.ImageField(default='default_profile.png', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
