# Generated by Django 3.2.7 on 2022-01-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='active',
        ),
        migrations.AlterField(
            model_name='trade',
            name='fecha_creado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
